version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lab1
    ports:
      - "3306:3306"
  lab2:
    image: daneidmark/bank:0.0.2
    environment:
      - MYSQL_HOST=mysql
      - RISK_URL=https://riskService:8081
      - USER_URL=http://userService:8082
    ports:
      - "8080:8080"
    links:
      - mysql
  riskService:
    image: daneidmark/risk:0.0.1
    ports:
      - "8081:8080"
  userService:
    image: daneidmark/user:0.0.1
    ports:
      - "8082:8082"